project1/project1/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project1.data.Entities;
using project1.logic.Models;
using project1.logic.Interfaces;

namespace project1.Controllers
{
    public class CustomersController : Controller
    {
        private readonly restaurantContext _context;

        public IRepository Repo { get; }

        public CustomersController(IRepository repo)
        {
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));
            _context = new restaurantContext();
        }
        /*
        public CustomersController(restaurantContext context)
        {
            _context = context;
        }
        */
        // GET: Customers
        
        public IActionResult Index(string search = "")
        {
            var store = 1;
            if (search == null)
                search = "";
            try
            {
                store = int.Parse(TempData["storeNum"].ToString());
            }
            catch
            {
                return Redirect("../Locations");
            }
            TempData["storeNum"] = store;
            TempData.Keep();
            List<Customers> model = Repo.GetCustomerList(store, search);
            return View(model);
        }


        // GET: Customers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .Include(c => c.StorenumNavigation)
                .FirstOrDefaultAsync(m => m.Name == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            ViewData["Storenum"] = new SelectList(_context.Location, "Storenum", "Name");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,Storenum,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Storenum"] = new SelectList(_context.Location, "Storenum", "Name", customer.Storenum);
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["Storenum"] = new SelectList(_context.Location, "Storenum", "Name", customer.Storenum);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Address,Storenum,Phone")] Customer customer)
        {
            if (id != customer.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Storenum"] = new SelectList(_context.Location, "Storenum", "Name", customer.Storenum);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .Include(c => c.StorenumNavigation)
                .FirstOrDefaultAsync(m => m.Name == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var customer = await _context.Customer.FindAsync(id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(string id)
        {
            return _context.Customer.Any(e => e.Name == id);
        }
    }
}

project1/project1/Controllers/MainMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using project1.logic.Interfaces;
using project1.logic.Models;

namespace project1.Controllers
{
    public class MainMenuController : Controller
    {
        // GET: MainMenu
        public ActionResult Index()
        {
            return View();
        }

        /*public ActionResult Index(string hidden)
        {
            TempData[
            return View();
        }*/

        public ActionResult ChangeMenu(string main)
        {
            
            if (main == "customerList")
                return Redirect("../Customers");
            else if (main == "addCustomer")
                return Redirect("../AddCustomer");
            else if (main == "displayMenu")
                return Redirect("../DisplayMenu");
            else
                return Redirect("../FoodOrders");
        }
        [HttpPost]
        public ActionResult Index(string locale)
        {
            int storenum;
            string location = "";
            try
            {
                location = locale.Substring(1);
            }
            catch
            {
                return Redirect("../Locations");
            }
            try
            {
                storenum = int.Parse(locale[0].ToString());
            }
            catch
            {
                storenum = 1; 
            }


            TempData["location"] = location;
            TempData["storeNum"] = storenum;
            TempData.Keep();
            Locations model = new Locations(location, storenum); 
            return View(model);
        }

        // GET: MainMenu/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MainMenu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MainMenu/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MainMenu/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MainMenu/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MainMenu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MainMenu/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

project1/project1/Controllers/PlaceOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using project1.logic.Interfaces;

namespace project1.Controllers
{
    public class PlaceOrderController : Controller
    {
        public IRepository Repo { get; }


        public PlaceOrderController(IRepository repo)
        {
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));

        }
        [HttpPost]
        public ActionResult Index(string patron)
        {
            if (patron == null)
                return Redirect("../Customers");
            TempData["customer"] = patron;
            TempData.Keep();
            return View(Repo.GetMenuViewModel());
        }

        // GET: PlaceOrder
        public ActionResult Index()
        {
            return View();
        }




        // POST: PlaceOrder/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            
            
            var checkered = collection["isChecked"];
            var name = TempData["Customer"].ToString();
            bool place = Repo.PlaceOrder(checkered, name);

            if(place)
                return View();
            return Redirect("../MainMenu");
        }


    }
}

project1/project1/Views/Customers/Create.cshtml
@model project1.data.Entities.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Storenum" class="control-label"></label>
                <select asp-for="Storenum" class ="form-control" asp-items="ViewBag.Storenum"></select>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

project1/project1/Views/Customers/Delete.cshtml
@model project1.data.Entities.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StorenumNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StorenumNavigation.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Name" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

project1/project1/Views/Customers/Details.cshtml
@model project1.data.Entities.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StorenumNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StorenumNavigation.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Name">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

project1/project1/Views/Customers/Edit.cshtml
@model project1.data.Entities.Customer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Name" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Storenum" class="control-label"></label>
                <select asp-for="Storenum" class="form-control" asp-items="ViewBag.Storenum"></select>
                <span asp-validation-for="Storenum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

project1/project1/Views/Customers/Index.cshtml
@model List<project1.logic.Models.Customers>

@{
    ViewData["Title"] = "Index";
}

<h2>Customer List at Zhou Mama</h2>

<p>
    <a asp-action="Create">Customers</a>
</p>

<form method="post" action="@Url.Action("Index", "PlaceOrder")">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Phone
                </th>
                <th>
                    Address
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                
                <tr>
                <td>
                <input type="radio" name="patron" id="@Html.DisplayFor(modelItem => item.name)"
                       value="@Html.DisplayFor(modelItem => item.name)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>

                </tr>
                
            }
        </tbody>
    </table>

    <button type="submit">Order for Customer</button>
</form>
    <form method="post" action="@Url.Action("Index", "Customers")">
        <input type="text" name="search" />
        <button type="submit" name="searchbar">Search</button>
    </form>
    <form method="post" action="@Url.Action("Index", "MainMenu")">
        <button type="submit">Go back</button>
    </form>